### ISSUE TITLE
Hierarchical Consensus (B1) MVP

### ISSUE THREAD

**Issue by adlrocha** [filecoin-project/eudico#28]
This is the main entrypoint for the sharding MVP. I'll try to keep here a checklist with `TODOs` and issues to be implemented for the MVP.

* [x] Shard Actor
  * [x] Add
  * [x] Join
  * [x] #53
  * [x] #59
  * [x] #61
  * [x] #62
  * [x] https://github.com/filecoin-project/eudico/pull/85
  * [x] Cross-net messages handling (#85, #88, #93, #94, #118, #119. #92)
  * [x] #80
  * [x] Unit tests

* [x] Eudico
  * [x] https://github.com/filecoin-project/eudico/issues/27
  * [x] https://github.com/filecoin-project/eudico/issues/33
  * [x] https://github.com/filecoin-project/eudico/issues/35
  * [x] https://github.com/filecoin-project/eudico/issues/36
  * [x] https://github.com/filecoin-project/eudico/issues/25
  * [ ] https://github.com/filecoin-project/eudico/issues/24
  * [x] https://github.com/filecoin-project/eudico/issues/38
  * [x] https://github.com/filecoin-project/eudico/issues/26
  * [x] #39
  * [x] #40
  * [ ] https://github.com/filecoin-project/eudico/issues/31
  * [x] https://github.com/filecoin-project/eudico/issues/32
  * [x] #50
  * [x] Cross-shard Filecoin transaction (#85, #88, #93, #94, #118, #119. #92)
  * [x] Atomic execution protocol (#133, #137, #138)
  
* [ ] Testing / Benchmarks
   * [ ] https://github.com/filecoin-project/eudico/issues/34
   * [ ]  https://github.com/filecoin-project/eudico/issues/9
   * [ ] #84

* [ ] Post-MVP backlog
  * [ ] https://github.com/filecoin-project/eudico/issues/37
  * [ ] #54
  * [x] https://github.com/filecoin-project/eudico/issues/29
  * [ ] #79

* [ ] Docs

* [ ] Housekeeping
  * [x] #78

**Comment by adlrocha** [comment]
Closing MVP stage. From now on, low-level developments and issue regarding hierarchical consensus can be tracked [in this project](https://github.com/filecoin-project/eudico/projects/1)
